version: 2.0
# Run using circleci local execute --job build
orbs:
  hello: circleci/python:3.6.2-stretch-browsers

workflows:
  "Hello Workflow":
    jobs:
      - hello/hello-build

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Printing Hello world"
          command: echo "hello world"
      - run:
          name: "Creating new directory.."
          command: |
            mkdir output
            cd output
            mkdir artifacts
            mkdir test_results
      - run:
          name: "Updrading pip"
          command: pip install --user pip
      - run:
          name: "Execution hello.py python file"
          command: python hello.py
      - run:
          name: "Getting numpy dependency"
          command: pip install --user numpy 
      - run:
          name: "Execution np.py python file"
          command: python np.py
      - store_artifacts:
          name: "Saving result in a file"
          path: output/artifacts
          destination: reports
      - store_test_results:
          path: output/test_results
