version: 2.0
# Run using circleci local execute --job build

jobs:
  one:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Run hello.py
          command: |
            . venv/bin/activate
            python hello.py

  two:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies

      - run:
          name: Installing numpy
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install numpy

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies

      - run:
          name: Run np.py
          command: |
            . venv/bin/activate
            python np.py

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
