aliases:
  - install_np: &install_np
      name: Installing numpy
      command: |
        python3 -m venv venv
        . venv/bin/activate
        pip install numpy
  - run_np: &run_np
      name: Run np.py
      command: |
        . venv/bin/activate
        python np.py
  - run_hello: &run_hello
      name: run tests
      command: |
        . venv/bin/activate
        python hello.py test
  - env: &env
      - image: circleci/python:3.6.4
  - docker_env: &docker_env
      docker:
        - image: circleci/python:3.6.4

version: 2
jobs:
  build:
    <<: *docker_env
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies

      - run: *install_np
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies

      - run: *run_np
      - run: *run_hello
      - store_artifacts:
          path: test-reports
          destination: test-reports
