version: 2.0
# Run using circleci local execute --job build

jobs:
  one:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/python:3.6.4
    steps:
      - run: echo "Running job 1"
      - checkout # check out the code in the project directory
      - run:
          name: "Printing Hello world"
          command: echo "hello world"
      - run:
          name: "Creating new directory.."
          command: |
            mkdir output
            cd output
            mkdir artifacts
            mkdir test_results
      - run:
          name: "Updrading pip"
          command: pip install --user pip
      - run:
          name: "Execution hello.py python file"
          command: python hello.py

    two:
      docker:
        -image: circleci/python:3.6.4
      steps:
        - run: echo "Running job 2"
        - checkout
        - run:
          name: "Getting numpy dependency"
          command: pip install --user numpy
        - run:
          name: "Execution np.py python file"
          command: python np.py test

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
